
$entries = Import-Clixml "C:\python\mcoc\_entries.xml"

$champMap = @{}
# Avengers / Heroes
$champMap['abomination'] = 'Abomination'
$champMap['abim'] = 'Abomination (Immortal)'
$champMap['absorbingman'] = 'Absorbing Man'
$champMap['abyss'] = 'Abyss'
$champMap['adam'] = 'Adam Warlock'
$champMap['adamwarlock'] = 'Adam Warlock'
$champMap['adaptoid'] = 'Super-Adaptoid'
$champMap['aeg'] = 'Aegon'
$champMap['aegon'] = 'Aegon'
$champMap['agentvenom'] = 'Agent Venom'
$champMap['agv'] = 'Agent Venom'
$champMap['airwalker'] = 'Air-Walker'
$champMap['amcha'] = 'America Chavez'
$champMap['anni'] = 'Annihilus'
$champMap['antfu'] = 'Ant-Man (Future Variant)'
$champMap['antman'] = 'Ant-Man'
$champMap['antivenom'] = 'Anti-Venom'
$champMap['antisbt'] = 'Anti-Venom'
$champMap['apo'] = 'Apocalypse'
$champMap['apocalypse'] = 'Apocalypse'
$champMap['ares'] = 'Ares'
$champMap['arc'] = 'Arcade'
$champMap['archangel'] = 'Archangel'
$champMap['atma'] = 'Archangel'
$champMap['ava'] = 'White Tiger (Ava Ayala)'
$champMap['avx'] = 'Alliance vs X-Men (Content)'
$champMap['aw'] = 'Alliance War (Content)'
$champMap['aol'] = 'Act of Legacy (Content)'
$champMap['a1'] = 'Tutorial Data'
$champMap['a8'] = 'Act 8 Content'
$champMap['bast'] = 'Bast'
$champMap['beast'] = 'Beast'
$champMap['bhmt'] = 'Black Hammer (Boss)'
$champMap['bishn'] = 'Bishop'
$champMap['bishop'] = 'Bishop'
$champMap['blade'] = 'Blade'
$champMap['blumrvl'] = 'Blue Marvel'
$champMap['bull'] = 'Bullseye'
$champMap['bullseye'] = 'Bullseye'
$champMap['capb'] = 'Captain Britain'
$champMap['capsw'] = 'Captain America (Sam Wilson)'
$champMap['carserp'] = 'Serpent (Car Boss)'
$champMap['cassie'] = 'Cassie Lang'
$champMap['col'] = 'Colossus'
$champMap['colossus'] = 'Colossus'
$champMap['cnef'] = 'Count Nefaria'
$champMap['cnova'] = 'Nova (Captain)'
$champMap['crv'] = 'Corvus Glaive'
$champMap['cvbw'] = 'Black Widow (Civil War)'
$champMap['cyc90'] = 'Cyclops (90s)'
$champMap['cyclops'] = 'Cyclops'
$champMap['dani'] = 'Dani Moonstar'
$champMap['daz'] = 'Dazzler'
$champMap['dbotu'] = 'Doctor Doom (Bot)'
$champMap['ded'] = 'Deadpool'
$champMap['dom'] = 'Domino'
$champMap['doom'] = 'Doctor Doom'
$champMap['dor'] = 'Dormammu'
$champMap['dormammu'] = 'Dormammu'
$champMap['dplplat'] = 'Deadpool (Platpool)'
$champMap['drac'] = 'Dracula'
$champMap['dracula'] = 'Dracula'
$champMap['drstrange'] = 'Doctor Strange'
$champMap['dust'] = 'Dust'
$champMap['dthns'] = 'Deathtrap'
$champMap['dun'] = 'Dungeons (Content)'
$champMap['elsa'] = 'Elsa Bloodstone'
$champMap['elsabloodstone'] = 'Elsa Bloodstone'
$champMap['emma'] = 'Emma Frost'
$champMap['emmafrost'] = 'Emma Frost'
$champMap['f4'] = 'Fantastic Four Saga'
$champMap['frnk'] = 'Franken-Castle'
$champMap['galan'] = 'Galan'
$champMap['ghru'] = 'Ghost Rider (Universe)'
$champMap['ghostrider'] = 'Ghost Rider'
$champMap['glad'] = 'Gladiator'
$champMap['gladiator'] = 'Gladiator'
$champMap['glyk'] = 'Glykon'
$champMap['gmast'] = 'Grandmaster'
$champMap['gmaster'] = 'Grandmaster'
$champMap['grndmstr'] = 'Grandmaster'
$champMap['gorr'] = 'Gorr the God Butcher'
$champMap['gp'] = 'System Global Passive'
$champMap['guard'] = 'Guardsman'
$champMap['guardsman'] = 'Guardsman'
$champMap['herc'] = 'Hercules'
$champMap['hercules'] = 'Hercules'
$champMap['heim'] = 'Heimdall'
$champMap['heimdall'] = 'Heimdall'
$champMap['highevo'] = 'High Evolutionary'
$champMap['hitmon'] = 'Hit-Monkey'
$champMap['hitmonkey'] = 'Hit-Monkey'
$champMap['hlklng'] = 'Hulkling'
$champMap['hulkim'] = 'Hulk (Immortal)'
$champMap['hulkrag'] = 'Hulk (Ragnarok)'
$champMap['hvk'] = 'Havok'
$champMap['havok'] = 'Havok'
$champMap['hyp'] = 'Hyperion'
$champMap['hyperion'] = 'Hyperion'
$champMap['iheart'] = 'Iron Heart'
$champMap['iim'] = 'Iron Man (Infamous)'
$champMap['invwo'] = 'Invisible Woman'
$champMap['ironfist'] = 'Iron Fist'
$champMap['ironman'] = 'Iron Man'
$champMap['jess'] = 'Jessica Jones'
$champMap['jjj'] = 'J. Jonah Jameson'
$champMap['jub'] = 'Jubilee'
$champMap['jubilee'] = 'Jubilee'
$champMap['joov'] = 'Jubilee (Variant)'
$champMap['kangimp'] = 'Kang (Impostor)'
$champMap['kangsup'] = 'Kang (Superior)'
$champMap['kate'] = 'Kate Bishop'
$champMap['korg'] = 'Korg'
$champMap['krvn'] = 'Karven'
$champMap['ktyp'] = 'King Thor'
$champMap['ld'] = 'Lady Deathstrike'
$champMap['leader'] = 'The Leader'
$champMap['lotan'] = 'Leviathon Tide'
$champMap['luma'] = 'Luma'
$champMap['magik'] = 'Magik'
$champMap['maes'] = 'Maestro'
$champMap['maestro'] = 'Maestro'
$champMap['mady'] = 'Madelyne Pryor'
$champMap['maker'] = 'The Maker'
$champMap['mantis'] = 'Mantis'
$champMap['mbaku'] = 'M-Baku'
$champMap['mgnx'] = 'Magneto (X-Men)'
$champMap['mkt'] = 'Makkari'
$champMap['mls'] = 'Mole Man'
$champMap['morb'] = 'Morbius'
$champMap['mojo'] = 'Mojo'
$champMap['mrkn'] = 'Mr. Knuckles'
$champMap['mysto'] = 'Mysterio'
$champMap['nam'] = 'Namor'
$champMap['namor'] = 'Namor'
$champMap['nec'] = 'Necropolis (Content)'
$champMap['nmaster'] = 'Nightmare (Master)'
$champMap['nrthstr'] = 'Northstar'
$champMap['northstar'] = 'Northstar'
$champMap['nico'] = 'Nico Minoru'
$champMap['nim'] = 'Nimrod'
$champMap['nova'] = 'Nova'
$champMap['odin'] = 'Odin'
$champMap['onslaught'] = 'Onslaught'
$champMap['ore'] = 'Omega Red'
$champMap['ored'] = 'Omega Red'
$champMap['oro'] = 'Storm (Ororo Variant)'
$champMap['osntl'] = 'Old Man Logan'
$champMap['peni'] = 'Peni Parker'
$champMap['phx'] = 'Phoenix'
$champMap['phoenix'] = 'Phoenix'
$champMap['photon'] = 'Photon'
$champMap['pixie'] = 'Pixie'
$champMap['pnshru'] = 'Punisher 2099'
$champMap['profx'] = 'Professor X'
$champMap['proxima'] = 'Proxima Midnight'
$champMap['prowl'] = 'Prowler'
$champMap['psymn'] = 'Psylocke'
$champMap['ptrt'] = 'Patriot'
$champMap['purg'] = 'Purgatory'
$champMap['pve'] = 'PVE Content'
$champMap['pvitr'] = 'Colossus (Piotr Variant)'
$champMap['qckslvr'] = 'Quicksilver'
$champMap['raid'] = 'Raids (Content)'
$champMap['reed'] = 'Mister Fantastic'
$champMap['redg'] = 'Red Guardian'
$champMap['rgob'] = 'Red Goblin'
$champMap['rokt'] = 'Rocket Raccoon'
$champMap['rogue'] = 'Rogue'
$champMap['ruby'] = 'Ruby Thursday'
$champMap['sand'] = 'Sandman'
$champMap['sb'] = 'Story Battle (Content)'
$champMap['scrm'] = 'Scream'
$champMap['scrpn'] = 'Scorpion'
$champMap['scytalis'] = 'Scytalis'
$champMap['sentinel'] = 'Sentinel'
$champMap['sentibot'] = 'Sentinel Bot'
$champMap['sentineloid'] = 'Sentineloid (Boss)'
$champMap['sentry'] = 'Sentry'
$champMap['sersi'] = 'Sersi'
$champMap['shang'] = 'Shang-Chi'
$champMap['shuri'] = 'Shuri'
$champMap['shthra'] = 'She-Hulk (Thanos Variant)'
$champMap['silk'] = 'Silk'
$champMap['skrull'] = 'Skrull'
$champMap['solv'] = 'Solvang'
$champMap['sorcsup'] = 'Sorcerer Supreme'
$champMap['spdr2099'] = 'Spider-Man 2099'
$champMap['spdrsprm'] = 'Spider-Man Supreme'
$champMap['spdrwmn'] = 'Spider-Woman'
$champMap['spham'] = 'Spider-Ham'
$champMap['spiderman'] = 'Spider-Man'
$champMap['spot'] = 'The Spot'
$champMap['sprl'] = 'Spiral'
$champMap['spunk'] = 'Spunk'
$champMap['sqch'] = 'Squirrel Girl'
$champMap['squirrelgirl'] = 'Squirrel Girl'
$champMap['srpnt'] = 'Serpent'
$champMap['ssable'] = 'Silver Sable'
$champMap['stlspdr'] = 'Steel Spider'
$champMap['stormr'] = 'Storm (Rogue Variant)'
$champMap['strf'] = 'Stryfe'
$champMap['supman'] = 'Cosmic Spider-Man'
$champMap['surf'] = 'Silver Surfer'
$champMap['swtch'] = 'Switch'
$champMap['tbe'] = 'Thor (Binary Variant)'
$champMap['terry'] = 'Terrax'
$champMap['tg'] = 'Tag System'
$champMap['thanos'] = 'Thanos'
$champMap['thechamp'] = 'The Champion'
$champMap['thing'] = 'The Thing'
$champMap['tnia'] = 'Titania'
$champMap['toad'] = 'Toad'
$champMap['torch'] = 'Human Torch'
$champMap['tm'] = 'Taskmaster'
$champMap['viv'] = 'Viv Vision'
$champMap['void'] = 'The Void'
$champMap['vox'] = 'Vox'
$champMap['vtd'] = 'Venompool'
$champMap['warmac'] = 'War Machine'
$champMap['wave'] = 'Wave'
$champMap['whttgr'] = 'White Tiger'
$champMap['wong'] = 'Wong'
$champMap['wrlk'] = 'Warlock'
$champMap['wwolf'] = 'Werewolf by Night'
$champMap['x23'] = 'X-23'
$champMap['x23u'] = 'X-23 (Uncanny)'
$champMap['ylb'] = 'Yellowjacket'
$champMap['zemo'] = 'Baron Zemo'
$champMap['zola'] = 'Arnim Zola'
$champMap['bong'] = 'Bong (Boss)'
$champMap['buddy'] = 'Buddy (Boss)'
$champMap['carl'] = 'Carl (Boss)'
$champMap['ceras'] = 'Ceras (Boss)'
$champMap['hnchpl'] = 'Henchman (Chapel)'
$champMap['iphyne'] = 'Iphyne (Boss)'
$champMap['karrie'] = 'Karrie'
$champMap['npc'] = 'NPC Enemy'
$champMap['daz'] = 'Dazzler'
$champMap['ave'] = 'Avengers (Synergy/Content)'
$champMap['mdk'] = 'Mordok'
$champMap['amra'] = 'Amra'
$champMap['zola'] = 'Arnim Zola'
$champMap['lotan'] = 'Leviathon Tide'

$groups = $entries | Group-Object { ($_.Id -split '_')[0] } | Sort-Object Name

$out = "C:\python\mcoc\champions_all.txt"
$sw = [System.IO.StreamWriter]::new($out, $false, [System.Text.Encoding]::UTF8)
$s80 = "=" * 80
$s80d = "-" * 80

$sw.WriteLine($s80)
$sw.WriteLine("Marvel Contest of Champions - チャンピオン全アビリティデータ")
$sw.WriteLine("ファイル: B64FC6A6D6243DB2A88B295572F5B5F145A66393.bin")
$sw.WriteLine("総エントリー数: $($entries.Count)  |  グループ数: $($groups.Count)")
$sw.WriteLine($s80)

foreach ($grp in $groups) {
    $prefix = $grp.Name
    $fullName = if ($champMap.ContainsKey($prefix)) { $champMap[$prefix] } else { "(不明)" }
    $sw.WriteLine("")
    $sw.WriteLine($s80)
    $sw.WriteLine("チャンピオン: $fullName  [prefix: $prefix]  (エントリー数: $($grp.Count))")
    $sw.WriteLine($s80d)
    $sw.WriteLine("  " + "アビリティID".PadRight(55) + "効果タイプ".PadRight(25) + "トリガー")
    $sw.WriteLine($s80d)
    foreach ($e in ($grp.Group | Sort-Object { $_.Id })) {
        $line = "  " + $e.Id.PadRight(55) + $e.Type.PadRight(25) + $e.Trigger
        $sw.WriteLine($line)
        if ($e.Condition -and $e.Condition.Length -gt 2 -and $e.Condition.Length -lt 300) {
            $sw.WriteLine("    >> 条件: $($e.Condition)")
        }
        if ($e.Filter -and $e.Filter.Length -gt 2 -and $e.Filter.Length -lt 300) {
            $sw.WriteLine("    >> フィルター: $($e.Filter)")
        }
    }
}
$sw.Close()
$fi = Get-Item $out
Write-Host "完了: $out ($([math]::Round($fi.Length/1MB,2)) MB / $($fi.Length) bytes)"
